### ISSUE TITLE
(May 5th) create microservice to manage sensors and to allow interfacing with sensor data

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#115]

**Comment by sstanovnik** [comment]
This post is used as a TODO list.

### Prerequisites
- [ ] prereq1

### Progress
- [ ] prog1

**Comment by sstanovnik** [comment]
I've made a simple diagram of what I think all this should look like. For reference on my thoughts at this point in time.

![mf2c-sensor-manager-arch-2019-02-13](https://user-images.githubusercontent.com/8071628/52699391-f59e9280-2f75-11e9-9372-673e143a7b67.png)

There are some prerequisites I have before beginning development, and they'll also likely help in refining the architecture. They're all listed in the TODO comment, but the application interfaces I require to be present are:

* Sensor list from the categorisation module through CIMI
* A data streaming interface, likely through CIMI, but this needs to be decided
* An agreement on the sensor driver value reporting format

As for the questions/concerns I have, also mentioned in the diagram:

1. We need a consistent format for a sensor definition in CIMI. I did not find one, so I assume this doesn't exist. I'd like to be consulted on my requirements when this is decided upon.
   * What I fear most is that a sensor definition will be `"temperature sensor"`, which is utterly useless. A description of the hardware connected is ideal.
2. My first idea is to reuse the CIMI notification mechanism for external clients to subscribe to sensor data. This may not be elegant, so I need advice.
3. We need access policies for sensor data. For starters, to make things simple, just "can read sensor data" and "can not read sensor data". I'd like advice on what is needed for this to be able to be configured.
4. Kind of tied to number 1, we need a one-to-many mapping between sensors (hardware) and outputs (environmental values). I'd like this to be handled by the categorisation component, along with e. g. what SI units a value is bound to. The sensor manager would then adapt its output values to these requirements, because some sensors may report, e. g. a different magnitude than what is requested. Clients would then be able to properly reason about the values returned.

**Comment by sstanovnik** [comment]
After some discussions, I've arrived at a new architecture for this. We can't use streaming through CIMI, so we'll use MQTT with a server that can handle authorization for us, all controlled by the sensor manager.

![mf2c-sensor-manager-arch-2019-03-13](https://user-images.githubusercontent.com/8071628/54265938-b06e8000-4576-11e9-9ea6-3d78363b9521.png)

An initial implementation of the things not communicating through CIMI has been done in [mf2c/sensor-manager](/mf2c/sensor-manager). Docker images have been published to Docker Hub. Work will resume after a CIMI interface has been created.

**Comment by ssgUPC** [comment]
mF2C/cimi#56 Added the sensor information into the CIMI resource schema (device)

**Comment by sstanovnik** [comment]
The sensor manager has been released. Repository at mf2c/sensor-manager and docs at readthedocs.
