### ISSUE TITLE
Sensor integration

### ISSUE THREAD

**Issue by giulianacarullo** [mF2C/mF2C#131]
Retrieve sensors existence & relative information from CIMI
needs #142

**Comment by jkennedyie** [comment]
Landscaper support on hold pending implementation of CIMI Delete integration.

**Comment by cjdcordeiro** [comment]
can you please elaborate on what's missing?

**Comment by svoorakk** [comment]
Cris, Can you please explain how to retrieve sensor information from CIMI through CIMI API?

**Comment by cjdcordeiro** [comment]
@ssgUPC provides this information though the device-dynamic resource

**Comment by svoorakk** [comment]
Can you please point me to the documentation on device-dynamic resource and sample data? Thanks!

**Comment by cjdcordeiro** [comment]
https://mf2c-project.readthedocs.io/en/latest/developer_guide/testing.html#add-the-device-dynamic-info but you should ask @ssgUPC if that's up to date

**Comment by svoorakk** [comment]
@ssgUPC can you please confirm the doc is up-to-date? Can you also let me know if device & myLeaderID can point to different device IDs? If so can you please explain these two attributes?

@cjcordeiro, does CIMI Events system support deletion of sensors? If not, is there a plan to add the capability?

**Comment by cjdcordeiro** [comment]
a Sensor is not a CIMI resource (https://github.com/mF2C/cimi/tree/master/server/src/com/sixsq/slipstream/ssclj/resources/spec), so it cannot be managed as one.

if sensor information is part of another resource, then you'd need to edit it.

**Comment by ssgUPC** [comment]
@svoorakk Well regarding the device and myLeaderID issue...what I can say, logically for a normal FN (I'm considering which is not an FL), it should be different...But the problem is that I'm storing the myLeaderID through the device-dynamic information....so to be aligned with CIMI schema, I need the CIMI provided ID for 'myLeaderID'....someone needs to provide the ID to my component....otherwise I can't be able to store the device-dynamic information.... by the way, I'm confirming that the doc is up-to-date and we tested it....It was working... 

 @cjdcordeiro, regarding the sensor information, as I promised I'll update the CIMI resource, within tomorrow...

**Comment by ssgUPC** [comment]
@svoorakk just to let you know...till now, the sensor information is not included...by tomorrow I'll do that...and will inform you...

**Comment by syc17** [comment]
May be I am confusing the issue, but is this myLeaderID the same as the one Policy passes to the CAU client?  If yes, I can get CAU client to write this to the mapped volume (the same one I wrote the agent credential to).

S

**Comment by ssgUPC** [comment]
@syc17 , to be honest, I don't know which one the CAU has....but I know, when you register a resource with the CIMI...the CIMI will automatically create a resource-id, in order to manage its resources... In case of the 'myLeaderID' which I'm expecting....it corresponds to the CIMI calculated resource-id for the leader node.

**Comment by syc17** [comment]
I think we need to ask Alejandro or Pau about this.  CAU client got this from the Policy block and in IT1, the policy did not send anything meaningful, just  a mock up value.

S

**Comment by svoorakk** [comment]
@cjcordeiro, does CIMI Events system support deletion from device-dynamic collection? If not, is there a plan to add the capability?

**Comment by svoorakk** [comment]
@cjcordeiro, does CIMI Events system support deletion from device-dynamic collection? If not, is there a plan to add the capability?

**Comment by svoorakk** [comment]
@cjdcordeiro,  does CIMI Events system support deletion from device-dynamic collection? If not, is there a plan to add the capability?

**Comment by cjdcordeiro** [comment]
yes can be added

**Comment by ssgUPC** [comment]
@svoorakk, I have already modified the device-dynamic resource definition and already made a PR but I think @cjdcordeiro will update it later because in my docker container I haven't added the information yet. Probably, by today I'll update my docker container and once it will update...I'll inform @cjdcordeiro to merge the PR
