### ISSUE TITLE
Store idKey in cloud CIMI/DC instance to support the Discovery, Authen and Categorisation process

### ISSUE THREAD

**Issue by syc17** [mF2C/mF2C#196]
This is related to #152.  During the authentication flow, CAU will authenticate a new FULL agent associated IDKey to check if it exists in the Cloud CIMI/DC.  This needs to be populated during the registration process.

**Comment by alxjand** [comment]
In order to store the IDKey in DC during the registration process, I need an extra field in the user information schema, otherwise, there is not place where I can store it. @cjdcordeiro, is it possible to include that extra field so when I register a new user I can submit the user password, username, email and also the IDKey?

**Comment by syc17** [comment]
Could you please let me know what is the endpoint and format of the REST request to the cloud CIMI/DC and the responses to expect.  I need to update the CAU code to align it with your work.  Thanks

**Comment by alxjand** [comment]
? 
Endpoint for what? Register new users?

**Comment by syc17** [comment]
@alxjand Once you have loaded the idKey into CIMI/DC, CAU needs to retrieve it via a REST call to CIMI/DC.  Perhaps @cjdcordeiro  know?

**Comment by cjdcordeiro** [comment]
> In order to store the IDKey in DC during the registration process, I need an extra field in the user information schema, otherwise, there is not place where I can store it. @cjdcordeiro, is it possible to include that extra field so when I register a new user I can submit the user password, username, email and also the IDKey?

the `user` resource cannot be changed. You'll need to put the IDKey someplace else, inn another resource, or simply use the CIMI ID of that user

**Comment by alxjand** [comment]
In that case, can you help me to create a new resource and load it into CIMI? 
Do you have a guide to do it? Unfortunately, I need a step by step tuto. It is something I have never done and unfortunately I dont think it is something I can find in the web.
I only need a 3 fields resource: user (no null), idkey and deviceID

**Comment by cjdcordeiro** [comment]
isn't the `user_profile` created during user registration as well? you can save it there

**Comment by alxjand** [comment]
I didnt know about the existence of the user_profile resource. Explicitly I dont create it when a user is registered, is it done in background?
Anyeay, as long as it is a resource created during the user registration and I can filter by user, yes, I can save the idkey there.
How can I have the idkey field in the user_profile?

**Comment by cjdcordeiro** [comment]
Get in touch with Roi

**Comment by syc17** [comment]
Alex, Instead of using two params 'IDKey' and 'CIMI userID' as you suggest in a private message : 
![image](https://user-images.githubusercontent.com/10448958/62310820-405b8a80-b482-11e9-931e-7b70ccab2e11.png)
why not take Cris' advice on 21 Jun above and just use 'CIMI userID'?

**Comment by syc17** [comment]
And to be honest, I still feel it is more optimal for the Agent's local ID block to validate the IDKey early on (see https://github.com/mF2C/mF2C/issues/152#issuecomment-488322013).  Cris said that there may not be network connectivity, if this is the case, how would the cau-client connect to CAU?  The CAU is not part of an Agent.  Do we assume that the CAU exists in each 'local network' (?each Agent is serviced by a dedicated CAU?) and will have internet connectivity?

**Comment by alxjand** [comment]
This is a brief summary of what we discussed by email and the actions done to solve this issue:

Unfortunately, we were unable to store the IDKey directly in the dataClay through the CIMI, however, we focused in the problem to be solved and the problem was that our colleagues that are working in the CAU detected the need of a method to validate that the IDKey they receive is genuinely generated by the Mf2c system.

In this order of ideas, what we did was to stop sending the IDKey in the docker-compose file as environment variable and instead of that, it is obtained directly from the cloud by the identification module using the user credentials as authentication method. 

According with the discussed and with the implemented solution, the CAU can trust the obtained IDKey and no IDKey validation is required anymore. 

The mentioned solution is implemented in the latest identification image (v2).

**Comment by alxjand** [comment]
This is a brief summary of the actions done to solve this issue:

As we explained in the issue 196, neither the IDKey nor any other sensitive or not sensitive information is sent to the agent as environment variable in the docker-compose file anymore. Instead of that, the IDKey is directly obtained in the agent from the cloud by the identification module using the user credentials as authentication method.  

Once the user has been successfully identified, the system provides both, the IDKey and the deviceID.

The mentioned solution is implemented in the latest mf2c/identification image (v2).
