### ISSUE TITLE
discuss the use of RPi as agents in the project

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#47]
Cheney was suggesting to use other edge devices instead to RPis.

Have a general discussion about this, including the all consortium.

@cketley should arrange and host this discussion.

I suggest having this discussion before the 20th

**Comment by rosogon** [comment]
@cketley , what other edge devices? What is the problem with RPis?

**Comment by cketley** [comment]
I've got two problem areas regarding Raspberry-Pi that I would like to see discussed:-
1. It has very weak security - the micro-SD card can simply be taken out of the R-Pi, put into a card-reader on a laptop etc and evil software installed e.g. rootkit, keylogger etc. The best solution to this problem that I can think of is to encrypt the entire hard-drive (= microSD card) but this will require a human to be there to enter a password on each boot (because putting the password into the boot loader means it can easily be read by the hacker). In a production system where it will be expected to run unattended e.g. in an airport or in a boat, this will not scale and will cause major problems with downtime of the production system. Another possible solution is to use boards that do not boot off a microSD card i.e. boot off eeprom. I know this is not a fully secure solution but most people are not able to read proms so it is an improvement in security.
2. Electronically I have doubts about the stability of the board. I've been running R-pis myself and the best uptime I've seen is just two weeks. I don't know what the cause of it is so I can't say for sure it's electronically unstable but it needs looking into.

Following on from this I'm attaching links to some details on other boards that are available. 
A list of boards:- https://docs.google.com/spreadsheets/d/e/2PACX-1vT_J1QkNQIFfMdcLisDUs4j-imyqwwsUpyn7RTKNYyz857TdT5PMlyeKTZ_lxemRIls-td9lAmupzo7/pubhtml
The best column to look at in the spreadsheet above is called Cores.
The article it belongs to:- http://linuxgizmos.com/ringing-in-2018-with-103-hacker-friendly-sbcs/

Looking at the lists there are two things that I've noticed:-
1. There's differences in the amount of memory that the other boards have. We don't have to be restricted to 1 GB. That would solve some performance problems.
2. They mostly use similar processors i.e. A7, A8, A9, A53 which are all ARM. 

The fact that they're using similar processors brings us back to the original starting point of this discussion which was whether or not to create an image for the ARM architecture. So this means we can move forward on building images for ARM and to separately discuss whether or not the R-Pi is the best choice. 

Please discuss. It's not my place to make the decision on this but I thought I ought to flag up some concerns I have.

**Comment by cjdcordeiro** [comment]
thanks for the inputs @cketley 

Please allocate some time during our Developers call next Wednesday for this. Send an email reminder to everyone so that those who don't usually attend are at least aware we are having this discussion and can attend if desired. 

Personally:
 1. I think we need to look at this from a provider perspective, meaning that, it is up to the user to choose which device to use. If we build a Docker compliant mF2C system, then a user can run it in many many different types of platforms, including RPi...and it is not our responsibility to secure his/her device. All we need to ensure is that the mf2c application itself is secure, not the device, cause we don't own it. So things like encrypting the SD-card is out of our capabilities (and responsibilities).
 2. your number 2) seems to be a very personal experience. Myself, I have 24h/7 RPis working for months without any downtime
 3. That list is very useful. In the past I've mentioned using some of those as alternatives to our optimization problem in IT-1, but the think you also need to take into account is that the community support for those boards is not as wide as for RPi...so for example, you won't find the mainstream OS distributions (like Raspbian, ResinOS, Ubuntu Mate) in many of those boards.

I think it is worth discussing this on Wed. nevertheless.

**Comment by alexbarcelo** [comment]
Some notes:

 - Raspberry Pi 3 is able to [boot from LAN](https://www.raspberrypi.org/blog/pi-3-booting-part-ii-ethernet-all-the-awesome/). Although there's no EEPROM, so no security here, because if you have hardware access you can put a laptop with a boot environment and crack the system easily. Been there, done that.
 - I see no "boot options" in the spreadsheet you send, so I will assume that all of them have the same security issues: they can either:
   - Boot from a non-encrypted storage, easily spoofable / changable
   - Require password entering on boot up
   - Have a basic PXE / LAN boot which can be hacked with a laptop and a crossover cable.
 - My personal experience with RPi >= 2 is that they are stable. In the past I have had issues due to the power supply and power management, but now I typically rolled my own 5V-lots-of-A dumb power supply, which work better than smart phone chargers. Ofc, RPi are not production-grade equipment so YMMV.

> The fact that they're using similar processors brings us back to the original starting point of this discussion which was whether or not to create an image for the ARM architecture. So this means we can move forward on building images for ARM and to separately discuss whether or not the R-Pi is the best choice.

That is something that I tried to bring up in our last meeting, and now you have exposed it much better than I could ever have ;) I completely agree on that.

**Comment by rosogon** [comment]
Regarding 1), maybe https://www.raspberrypi.org/products/compute-module-3/ can help.

**Comment by cankarm** [comment]
@cketley 
I don't see any problems in the issues you are pointing out, just because this is a development environment, used for research and testing. Therefore we use the most affordable and general purpose device that meets most of the requirements. More in details:

**Ad 1:** 
Regarding the weak security - you must understand that probably here only UC2, Boats, present a real threat. But here at the end, when you would go into real production, the a waterproof standard casing would be required (like IP67 standard) and also tempering switch could be developed to detect opening of the device. Also, using SD cards in production environment would not be the best approach, i think. 

**Ad 2:**
Similar conclusions as in previous comment. This is development environment. Electronic stability is made at the end, when you finally decide what you actually use. At this point you employ the device which is most sufficient and does not have a bunch of extras that you do not need and potentially present a new risk for malfunction or security hole for the production device.  

To finish, any general purpose computer share similar issues as rPIs. Usually a tailored software is able to monitor and surely detect some problems or software deviations, but the any device which resides in the premises of some user is vulnerable opening it, erasing disks, reading content, etc. Probalby Nuvla boxes cover something of this through SlipStream. But this is a production environment, not a research project.

**Comment by syc17** [comment]
I strongly agree with Matijac's comments, we must remember that we are a research project, we need to demo the capabilities of the mF2C platform; not to deliver a market version of the platform.  We should focus our energy on building the platform.

**Comment by syc17** [comment]
If necessary, we can provide some comments and suggestions for how to cover the perceived shortcomings of rPIs in the relevant deliverable/s to indicate that we are aware of issues related to production deployment.  But let's focus on practical work ;)
