### ISSUE TITLE
draft mF2C GDPR policies

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#55]

**Comment by syc17** [comment]
I think this has 2 aspects: 1) GDPR policy for mF2C user data 2) GDPR policy for user application data.  In my view, the mF2C system should built-in good GRPR-compliance mechanism where possible to ensure data are processed in a transparent and secure manner as well as  are available and audit-able etc.  but we will need a concise policy (declaration) regarding responsibility towards personal data etc.  Have anyone thought about what to do with the management data after a user application exited the mF2C system?  For example, if we keep a log (either in a database or blockchain) of the user application at runtime, should we let the user download it?  Delete it?  Archive it?

**Comment by cketley** [comment]
GDPR compliance is mandatory. 
It would be useful for us to be able to demonstrate at a review that we have used Privacy By Design, which is a principle written into the Directive.
We have at the moment a flag in the Agent Controller Security Library for privacy of the data flowing through MQTT etc.

**Comment by cjdcordeiro** [comment]
data retention is a good example of why we need a policy first. For me it depends on the scope. Application data should not be kept for long. Look at cloud computing - if you keep data for longer than compute, you pay for it, and if data is local, if you delete your machine/application you also delete your data.

For users and user-related data however, data retention should be long in my view

**Comment by syc17** [comment]
Cris, sounds reasonable regarding not keeping data longer than compute.  However, in GDPR, you need to keep records on how personal data are processed.    Perhaps there should be an option of letting user down the log once their application completed?

**Comment by cjdcordeiro** [comment]
but application data is not personal data. Providers won't be liable for the data your application produces. But yes, application data (logs basically) should be available to the user.

**Comment by syc17** [comment]
1.  We don't know what sort of data that a user application processes at runtime, e.g. a smart-health application would have personal data; the airport use case uses mobile phone mac(?) address, this allows the identification of a person indirectly.
2.  GDPR is not the same as the old data protection act, it is much stricter.  From what I've been reading, the providers ARE data processors, companies selling desk tops are not liable but service providers who sell compute/storage/network services are liable.  This is why we should make sure that mF2C can demonstrate that we have built-in mechanisms to support GDPR-compliance like encryption, AAA, CIA etc.  To be honest,  we don't necessarily have to do too much extra impl work as these mechanisms link into generic good security and housekeeping measures.  Our security library already covers some aspects (CI)  and adding blockchain would help with availability, trace-ability and transparency....
Here is a couple of links discussing a service provider's role: https://www.fieldfisher.com/media/3993765/the-gdprs-impact-on-the-cloud-service-provider-as-a-processor-mark-webber-privacy-data-protection.pdf
https://iapp.org/news/a/gdpr-killing-cloud-quickly/
It would be good if Ana could consult her legal department re how mF2C stands.  Obviously, it would be great if the articles are wrong.  Also, I think Jens mentioned that the Fog Consortium has a GDPR working party, we should see what they recommend.  And the info could help shape the mF2C policy :)

**Comment by cjdcordeiro** [comment]
1. that's one more reasons why we do not want to keep application data after service termination. The application owner might have received the consent to process that data but we haven't, so we can keep it after the application has already ended. 

Nevertheless, application data is still subject to discussion as we are not yet storing it...so far storage has been the user's responsibility 

Let's take others into this discussion. This is a "2 Weeks" priority so please try to fit in this discussion sometime within the next 10 days

**Comment by cketley** [comment]
More requirements:-
1. The consent to processing has to be captured to disk and stored for many years.
2. There must be a method on screen to identify young people and capture this information to disk too
3. The consent has to relate to some kind of list of uses that the data will be put to. This list might change. The consent plus list must also be captured to disk.
4. the onscreen consent page _**must**_ include your purposes for processing their personal data, your retention periods for that personal data, and who it will be shared with
5. There's a long list of information that needs to be displayed to the user at consent time. Here's a list from the UK regulator [https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/right-to-be-informed/](url)
6. Data subjects have the right to request access to data about them. There's a time limit to respond so there needs to be some kind of ticketing system (or link to a ticketing system) with breach notification. Or something like that. I realise that this is a heavy technical requirement so some discussion and ideas on this would be useful.
7. Data subjects have the right to have data about them corrected or made complete. This implies a database maintenance procedure and gui. Also a ticketing system or something like that.
8. There is a right to be forgotten for Data Subjects. But it's not an absolute right so the technical process has a human process in the middle to make decisions on it.
9. There is a right of restriction which means the data can be stored but not used. This implies some kind of flag that our programs respect regarding whether or not to process a piece of data.
10. There is a right of portability meaning Data Subjects can access and download data about themselves in a portable format. 
11. Data Subjects have an absolute right to prevent the use of data about them in direct marketing. This implies the systems recognise the use is direct marketing and the programs respect some kind of flag to block processing on a person-by-person basis. There's also a qualified right in other circumstances so this implies a human intervention in the process to make a decision.
12. Regulations on automated decision making and profiling will probably apply in UC3. But it's a little complicated. See this UK regulator link for details:- [https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/rights-related-to-automated-decision-making-including-profiling/](url). This implies that the processing is being done in some kind of background process or backend subsystem separate from the main system, which in turn implies all of the processing in points 6 thru 10 must be replicated in the backend and some provision for doing the consent process in points 1 thru 5 must be done via email or similar.
13. The accounting requirements are extensive :- 
13a. recording and reporting of data breaches - implies we have some way to detect them too
13b. documented security procedures
13c. documented processing procedures
13d. impact assessments for high risk situations - I would say anything involving a credit card would fall into this category
14. Transfers of data outside the EU are likely to happen. The rules are complicated. See this link from the UK regulator: [https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/international-transfers/](url) A minimal approach would be to simply ban all movements outside of the EU which implies some mechanism that blocks the movement. I've been thinking along the lines of a filtering application firewall. Something more sophisticated than blocking all movements would be better though which implies a rule base for deciding what is allowed or not. This has to be discussed.
15. There's exemptions from all of this for national security, law enforcement and other things, which implies a mechanism to recognise this exemption and then apply overrides. Audit trails recording this use of exemption would be required too. But complicating this even more is the fact that some EU countries have additional exemptions , which implies this must be recognised too and recorded in the audit trail.
16. I haven't included the regulations on the lawful basis of processing because it's not a technical issue.
17. Personal data must not be kept for longer than is necessary. This implies a garbage collection process and timestamp.

**Comment by syc17** [comment]
I met a researcher from Brunel Univ law centre who specialises in GDPR today and I posed my questions to her.  I would like to share the answers with you all:
1)	Infrastructure and Platform as a Service Providers indeed have the role of Data Processor (at the very least) under article 26(2)
2)	GDPR’s focus is on doing the process right, i.e. what have you done to ensure compliance with GDPR.    For service providers who provide resources for users to run applications to process personal data, they should:
a.	review the security of their infrastructure, bring it up to standard 
b.	keep good records so the data controller (the holder of the data) can perform an audit if he/she so wishes
c.	regularly review their security and data management practices to make sure that they are still up2date and fit for the purpose.
3)	There is no formal white list of qualifying non-EU countries that personal data can be processed under GDPR.  You need to rely on your judgement; countries that have a good legal framework and records of complying with human rights etc. would most likely be OK.  Obviously, the individual companies still need to demonstrate GDPR-compliancy.

It would seem to me that my comment higher up regarding building in GDPR-compliance mechanism (e.g. AAA and encryption plus logging etc.)  would help mF2C as a P/IaaS provider demonstrate compliance regardless of what data are processed by the user application.

Regarding point 3), there is no whitelist  for creating a lookup table.  It would seem to me that the user will have to declare if they allow their data be processed outside of the EU (via a flag???)   (I don't think we should go down the path of categorising user data in great details.  The less mF2c knows the better[simplest]) Regarding the case of the boat use case, it may not even be relevant (unless the user application data is subject to security clearance, which doesn't sounds like it) as the boat is running mF2C which should be GDPR-compliant and we may argue that the data processor is GPDR-compliant even though it is (temporary) in an non-EU country.

**Comment by cketley** [comment]
Excellent comments from Shirley 
Responding to point 2 - Yes paperwork process is a big part of gdpr. I see our role as focusing on technical issues rather than process issues. However, we can make it easier (or harder!) for the data controller/processor to do their job and also for the user to use the systems provided. 
Responding to point 3 - equivalence of other countries is of technical interest because it creates a whitelist of geo-locations.  From what I can see the EU-USA Privacy Shield is still in force though it might collapse as Safe Harbor did. This implies a date in the system at which it is or isn't in force.
Also Japan is the late stages of agreeing with the EU on gdpr equivalence. It's not yet fully agreed but is expected to. This implies a date that it comes into force. South Korea is attempting to do the same.
Also note that non-EU members of the EEA are within the gdpr zone. Also Brexit will have some impact.
Here's a page from the EU:- 
https://gdpr-info.eu/issues/third-countries/
Quote:- "At the time that the General Data Protection Regulation became applicable, the third countries which are counted as secure countries are: Andorra, Argentina, Canada (only commercial organisations), Faroe Islands, Guernsey, Israel, Isle of Man, Jersey, New Zealand, Switzerland, Uruguay and USA (if the receiver belongs to the Privacy Shield). Data transfer to these countries is expressly permitted."
To complicate things individual organisations outside the EU can have data sent to them so long as they comply with Article 46. This page lists the rules:- https://gdpr-info.eu/art-46-gdpr/
To complicate things even further there's a lot of exemptions for law enforcement etc, which means we need a technical means to give Police and AntiTerrorist people etc access to our data (although a process to deal with the legal issues is outside of the scope of this project).
Interesting point about the boat temporarily leaving the EU with private data. Maybe some technical control is required to be aware that the data is being moved out of the EU. Would data collected while outside of the EU then require gdpr compliance when the boat moves into EU waters?
I'm also aware that in the recent M18 Review by the commission it was commented that there wasn't any  security-by-design (and by implication privacy-by-design). So I guess this means we should at least design the features into the systems even if they're never actually used.

**Comment by cjdcordeiro** [comment]
Lara is following up on this

**Comment by cankarm** [comment]
GDPR policies were introduced only for mF2C users (aka mF2C application developers). The example user consent was produced and evaluated. Next steps include implementation of the policies which is covered in mf2c/usermanagement#9 issue.
