### ISSUE TITLE
REST web svcs security for IT-2

### ISSUE THREAD

**Issue by jjensenral** [mF2C/mF2C#71]
connected to https://github.com/mF2C/secLib/issues/1

In the HTTP/REST/JESON implementation of CIMI, security can be implemented through RESTweb services security (ie token-based) or through JSON security (or both).  In contrast, the simpler ACL was the only option in IT-1.
As of mid Aug '18, several suggestions have been passed around in private emails, but have not been agreed, let alone thought through properly. We need to have proposals for what to do, including what role will be played by the CAU.
Once tasks are agreed, they need to be added to the security task list spreadsheet.

**Comment by syc17** [comment]
Adding to Jens' comments above:  intra-agent communication between blocks are done via the Docker's private network and is secure.  The issue is with inter-agent communication (both w/n and between layers), between 3rd party services and mF2C agents.  To me, I see the CAU as the identity keeper and is used to authenticate agents/services.  I am not so clear about authorisation at this stage as we have not yet discussed this.  Also here is the discussion document on ReST service security started by Jens :
[restful.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b4746420733320012adba65/125516c66e82c728ace21e0d46fa9189378496a5cda5fd53b652fa912a5265296b51fa2f7387e57be61a7a505c0e46ac415e5c42afafdb2bf4a42062c80d55b98e30063e937f03a6aa8317b500bf238d4a8dbeb58b48c8ed3c37aa.docx)

**Comment by cjdcordeiro** [comment]
regarding the communication between blocks...it might be out of scope but if we have the time and motivation for it, I'd love to also do a security analysis of the communication in between containers. Any finding and/or improvements would be welcome and highly visible in the Docker community

**Comment by cjdcordeiro** [comment]
discussed during the F2F meeting. The outcome is now being addressed in tickets #76 and #77

**Comment by syc17** [comment]
![AugmentCAU.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b4746420733320012adba65/125516c66e82c728ace21e0d46c9819d2e878dbdacc88a01e81fe086264c22703d46f96925dce72bbd442858570e4faf10505f44fafa8f78f0e43c22984019af80330b2b9b645bf9fa9015ad03bb2a8a4a86beb98d4fc5eb3527ef8e9d02.png)

CAU client could be used to provide an interface for an agent to obtain public key info from and authenticate with a CAU.  Pending the requirements for data security and privacy (use of encryption and signature), we could also move most of the functions from the security lib to the CAU so it could offer a loosely coupled service to an agent if needed.
