### ISSUE TITLE
define workflow for the client authz

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/mF2C#77]
- who issues and how is the OIDC token issues to the requesting component?
 - which kind of token? expirable? unique per agent?

**Comment by syc17** [comment]
This is in progress, Jens and I are discussing the pros and cons of using standalone JWT and OiDC/OAuth protocols.  I have made a slight modification to the proposed flow, if we use a self-contained JWT access token, CIMI uses the local CAU-Client to verify the signature rather than calling the CAU (the Auth server).  Note that Agent0.LCM is in reality only doing one extra step: getting the access token via the local CAU-client.  As far as I understand, CIMI  already (or should be): 1) validates resource requests, 2) hands out a session cookie which the client needs to send back in the http header for each subsequent call.
![Authz.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b4746420733320012adba65/125516c66e82c728ace21e0d46c9818e2b98c1e5cdf9ad4cae58f3806b1c65267000a02976d6ba70be132800575f4eaa425e0c12aef9db39baa47e21d40854b088270a36d43703adbf881eba04bb288c4e86b2ba8e4ec7fa70.png)

Another flow that we are investigating is to let Traefik handles token translation in a flow with:
1. the client sending a ID token which Traefik intercepts.  
2. Traefik calls a (KeyCloak? or script?) gatekeeper which in turn calls the Auth Server (AS) to exchange the token for a self-contained access token.
3) If an access token is retrieved successful and the defined scope is OK, traefik passes the client request to the target CIMI resource to handle.

**Comment by syc17** [comment]
Investigating adopting RFC7523 OAuth JWT Assertion Profiles to use a JWT for client authentication (and authorization if we are not delegating this to CIMI at the Relying Party end).  The approach:
1) leverages existing trust relationship (e.g. mF2C PKI)
2) does not require a direct user-approval step (i.e. user to login to Google/LinkedIn etc.)
3) Authentication is orthogonal to authorisation
4) uses JWT as the assertion framework.  We can use existing mF2C components: the AC Lib to create the JWT for the requesting client) and the CAU-Client to access the CAU Middleware (Identity manager).

**Comment by syc17** [comment]
Updated [document](https://docs.google.com/document/d/1h9CC5fT8vvbYO_iOUiOY7-f4Mf8RgW031nBUuw_HgjA/edit?usp=sharing) for discussion.  There is no points in assigning tasks if people disagree with the approach.  We need agreement first.

**Comment by cjdcordeiro** [comment]
better if we have a discussion with Cal. but at first sight, it seems ok. let me find the best time to have a chat all together

**Comment by syc17** [comment]
see https://docs.google.com/document/d/1h9CC5fT8vvbYO_iOUiOY7-f4Mf8RgW031nBUuw_HgjA/edit?usp=sharing
